### ISSUE TITLE
Cant find any Devices

### ISSUE THREAD

**Issue by J1K-Hub** [schroedan/homebridge-my-gekko#1]
Hi,
I got a Problem with connecting Homebridge-my-gekko with HomeKit.
Homebridge runs on macOS.
I entered the settings, but the devices are not shown into HomeKit.
The log File showed am message:
[4.3.2021, 23:57:03] Loaded plugin: homebridge-my-gekko@0.1.10
[4.3.2021, 23:57:03] Plugin 'homebridge-my-gekko' tried to register with an incorrect plugin identifier: 'my-gekko'. Please report this to the developer!
[4.3.2021, 23:57:03] Registering platform 'homebridge-my-gekko.myGEKKO'

Do you need more of the LogFile?
May someone help?

**Comment by J1K-Hub** [comment]
This entrys I found by using teh DebugMode:

Preparing Advertiser for 'homebridge-my-gekko 7DD6' using bonjour-hap backend!
[5.3.2021, 00:16:38] [homebridge-my-gekko] Platform finished launching
[5.3.2021, 00:16:38] [homebridge-my-gekko] Discovering accessories

Error: listen EADDRINUSE: address already in use :::30839
    at Server.setupListenHandle [as _listen2] (net.js:1318:16)
    at listenInCluster (net.js:1366:12)
    at Server.listen (net.js:1452:7)
    at EventedHTTPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/eventedhttp.ts:155:20)
    at HAPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:316:21)
    at Bridge.Accessory.publish (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1230:18)
    at BridgeService.publishBridge (/usr/local/lib/node_modules/homebridge/src/bridgeService.ts:210:17)
    at ChildBridgeFork.startBridge (/usr/local/lib/node_modules/homebridge/src/childBridgeFork.ts:172:24)

[5.3.2021, 00:16:38] [homebridge-my-gekko] Child bridge process ended
[5.3.2021, 00:16:38] [homebridge-my-gekko] Process Ended. Code: 1, Signal: null
Error: listen EADDRINUSE: address already in use :::37677
    at Server.setupListenHandle [as _listen2] (net.js:1318:16)
    at listenInCluster (net.js:1366:12)
    at Server.listen (net.js:1452:7)
    at EventedHTTPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/eventedhttp.ts:155:20)
    at HAPServer.listen (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:316:21)
    at Bridge.Accessory.publish (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1230:18)
    at BridgeService.publishBridge (/usr/local/lib/node_modules/homebridge/src/bridgeService.ts:210:17)
    at ChildBridgeFork.startBridge (/usr/local/lib/node_modules/homebridge/src/childBridgeFork.ts:172:24)


I'am runnig also the Plugin: homebridge-zp v1.1.7

**Comment by schroedan** [comment]
Hi,

sorry for my late reply. Just released a new version of the plugin which is a complete rewrite of the old one. Maybe the problem is gone now? Otherwise feel free to open a new issue.
